src/Entity/Currency.php
<?php
declare (strict_types = 1);
namespace MyApp\Entity;

use MyApp\Entity\EconomicZone;

class Currency
{
    private ?int $id = null;
    private string $name;
    private EconomicZone $zone;
    public function __construct(?int $id, string $name, EconomicZone $zone)
    {
        $this->id = $id;
        $this->name = $name;
        $this->zone = $zone;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(?int $id): void
    {
        $this->id = $id;
    }
    public function getName(): string
    {
        return $this->name;
    }
    public function setName(string $name): void
    {
        $this->name = $name;
    }
    public function getEconomicZone(): EconomicZone
    {
        return $this->zone;
    }
    public function setEconomicZone(EconomicZone $zone): void
    {
        $this->zone = $zone;
    }
}

templates/currencyController/addCurrency.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{ parent() }}
	Ajouter une monnaie
{% endblock %}
{% block content %}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-12 col-md-6 align-items-center">
				<h1 class="text-center text-primary fw-bold m-2">Ajouter une monnaie</h1>
				<form action="" method="post">
					<input type="text" id="name" name="name" class="form-control" placeholder="désignation" required>
					<select id="idZone" name="idZone" class="form-control" required>
						{% for z in zones %}
							<option value="{{z.id}}">{{z.nom}}</option>
						{% endfor %}
					</select>
					<div class="text-center">
						<input type="submit" value="Ajouter" class="btnbtn-primary m-2">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/currencyController/currency.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{ parent() }}
	Liste des monnaies
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-12 col-md-10 text-primary">
				<h1 class="text-center text-black">Liste des monnaies</h1>
				{% for currency in currency %}
					{{currency.id}}
					{{currency.name}}
                    <a href="index.php?page=updateCurrency&id={{currency.id}}"><i class="bi bi-pen-fill"></i></a>
                    <a href="index.php?page=deleteCurrency&id={{currency.id}}"><i class="bi bi-trash2-fill"></i></a><br/>
					{% endfor %}

				</div>
			</div>
		</div>
	{% endblock %}

templates/currencyController/listCurrency.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{ parent() }}
	Liste des monnaies
{% endblock %}
{% block content %}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-12 col-md-10">
				<h1 class="text-center text-dark">Liste des monnaies</h1>
				<div class="table-responsive">
					<table class="table table-hover">
						<thead>
							<tr>
								<th width="50%" scope="col" class="text-white">Monnaies</th>
								<th width="50%" scope="col" class="text-white">Zones économiques</th>
							</tr>
						</thead>
						<tbody>
							{% for c in currency %}
								<tr class="{{ cycle(['table- primary','table-secondary'], loop.index0) }}">
									<td>{{ c.name }}</td>
									<td>{{ c.economicZone.nom }}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/currencyController/updateCurrency.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{ parent() }}
	Modifier une monnaie
{% endblock %}
{% block content %}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-12 col-md-6 align-items-center">
				<h1 class="text-center text-primary fw-bold m-2">Modifier une monnaie</h1>
				<form action="" method="post">
					<input type="hidden" id="id" name="id" value="{{currency.id}}">
					<input type="text" id="name" name="name" class="form-control" placeholder="désignation" value="{{currency.name}}" required>
					<select id="idZone" name="idZone" class="form-control" required>
						{% for z in zones %}
							{% if z.id == currency.zone.id %}
								<option value="{{z.id}}" selected>{{z.nom}}</option>
							{% else %}
								<option value="{{z.id}}">{{z.nom}}</option>
							{% endif %}
						{% endfor %}
					</select>
					<div class="text-center">
						<input type="submit" value="Modifier" class="btn btn-primary m-2">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}